on:
  push:
    branches:
    - production
    - qa
    - development

jobs:
  tag-job:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        #fetch-tags: true  # don't bother with this one.  future self, this won't help you.
        fetch-depth: 0  # fetch-tags doesn't actually add --tags.  it just _allows_ tags.
    - name: Create new tag for version
      run: |
        BRANCH="$(git branch --show-current)"
        SHORTBRANCH="$( echo "$BRANCH" | sed -e 's/production/prod/' -e 's/development/dev/')"
        MAXTAG="$(git tag |grep -E -- "-${SHORTBRANCH}\$"|tr -dc '0-9\n'|sort -n|tail -1|grep . || echo 0)"
        NEWNAME=v$(( MAXTAG + 1 ))-$SHORTBRANCH
        git tag "$NEWNAME"
        git push origin "$NEWNAME"
